services:
  crud-rest-api:
    image: crud-rest-api:latest
    build: .
    restart: "no"
    ports:
      - "8080:8080"
  postgres:
    image: postgres:16.4
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: --
      POSTGRES_PASSWORD: --
      POSTGRES_DB: --
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  postgres_data: